intel/nn-hal

Intel_mkldnn_nn_hal/Android.mk, Intel_mkldnn_nn_hal/MklDnnDriver.cpp, Intel_mkldnn_nn_hal/MklDnnDriver.h, Intel_mkldnn_nn_hal/MklDnnPreparedModel.cpp, Intel_mkldnn_nn_hal/MklDnnPreparedModel.h, Intel_mkldnn_nn_hal/android.hardware.neuralnetworks@1.0-mkldnn.rc, Intel_mkldnn_nn_hal/service.cpp
It is a CPU hal based on mkldnn library.
Signed-off-by: cxie4 <chao.xie@intel.com>
=> Add Intel mkldnn nn hal

Android.mk, Intel_mkldnn_nn_hal/hal/Android.bp, Intel_mkldnn_nn_hal/libmkldnn/Android.bp, intel_nn_hal/Android.mk, intel_nn_hal/Driver.cpp, intel_nn_hal/dl/Android.mk, intel_nn_hal/dl/ie.mk, intel_nn_hal/dl/mkldnn.mk, intel_nn_hal/dl/mkldnn_plugin.mk, intel_nn_hal/graphAPI/IENetwork.h, intel_nn_hal/graphAPI/graphAPI.mk, intel_nn_hal/graphTests/graphTests.mk, intel_nn_hal/graphTests/helpers-test.hpp
Signed-off-by: Atul Vaish <atul.vaish@intel.com>
=> Enabling OPENVINO/DLDT to work with Celadon

Intel_mkldnn_nn_hal/README.md
=>  Updated the step of integrating MKL-DNN into MKL-DNN NN HAL in Intel_mkldnn_nn_hal/README.md.

intel_nn_hal/dl/ie.mk
Signed-off-by: Atul Vaish <atul.vaish@intel.com>
=> ie.mk file correction

intel_nn_hal/dl/ie.mk
Signed-off-by: Atul Vaish <atul.vaish@intel.com>
=> reverting ie.mk correction

intel_nn_hal/Driver.cpp
Tracked-On: OAM-83304
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>
=> Provide option to disable nn-hal for testing with cpu fallback

intel_nn_hal/Driver.cpp
=> Revert "Provide option to disable nn-hal for testing with cpu fallback"

intel_nn_hal/graphTests/helpers-test.hpp
=> Fix for klocwork reported error

Intel_mkldnn_nn_hal/hal/MklDnnPreparedModel.cpp, intel_nn_hal/Android.mk, intel_nn_hal/Executor.cpp, intel_nn_hal/PreparedModel.cpp, intel_nn_hal/graphAPI/IRLayers.h, intel_nn_hal/service.cpp
=> Fix for NNHAL1.2 klocwork issues and cflags added for SDL

Intel_mkldnn_nn_hal/hal/MklDnnPreparedModel.cpp, intel_nn_hal/Android.mk, intel_nn_hal/Executor.cpp, intel_nn_hal/PreparedModel.cpp, intel_nn_hal/graphAPI/IRLayers.h, intel_nn_hal/service.cpp
=> Fix for NNHAL klocwork issues and cflags added for SDL

Intel_mkldnn_nn_hal/hal/MklDnnPreparedModel.cpp, intel_nn_hal/Android.mk, intel_nn_hal/Executor.cpp, intel_nn_hal/PreparedModel.cpp, intel_nn_hal/graphAPI/IRLayers.h, intel_nn_hal/service.cpp
=> Fix for klocwork issues and cflags addition for SDL

intel_nn_hal/PreparedModel.cpp
=> Fix for klocwork critical issue in nn-hal1.1

intel_nn_hal/PreparedModel.cpp
=> Fix for klocwork critical issue in nn-hal1.1 for Q

intel_nn_hal/PreparedModel.cpp
=> Fix for klocwork critical issue in nn-hal1.2 for Q

intel_nn_hal/graphAPI/Android.bp
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>
=> Fix build error in Android 11 due to fPIC

BUILD.gn, gna_driver.cpp, intel_nn_hal/Driver.cpp, intel_nn_hal/Driver.h, intel_nn_hal/GnaPreparedModel.cpp, intel_nn_hal/GnaPreparedModel.h, intel_nn_hal/PreparedModel.cpp, intel_nn_hal/PreparedModel.h, intel_nn_hal/Utils.cpp, intel_nn_hal/Utils.h, intel_nn_hal/graphAPI/BuilderNetwork.h, intel_nn_hal/graphAPI/GnaNetwork.cpp, intel_nn_hal/graphAPI/GnaNetwork.h, intel_nn_hal/graphAPI/IRBuilder.cpp, intel_nn_hal/graphAPI/IRBuilder.h, intel_nn_hal/graphAPI/IRDocument.cpp, intel_nn_hal/graphAPI/IRLayer.cpp, intel_nn_hal/graphAPI/IRLayers.h, intel_nn_hal/graphAPI/builderLayerNorm/IRLayerNorm.cpp, intel_nn_hal/graphAPI/builderLayerNorm/IRLayerNorm.h, intel_nn_hal/graphAPI/builderLayerNorm/test_LN.cpp, intel_nn_hal/graphAPI/builderLayerNorm/tflite_Ln.cpp, intel_nn_hal/graphAPI/builderLayerNorm/tflite_Ln.h
- Adds support for GNA device
- Contains changes to support caching
=> Add support for GNA IP 

BasePreparedModel.cpp, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/include/Temp.h, ngraph_creator/operations/include/Reshape.hpp, ngraph_creator/operations/src/Reshape.cpp, ngraph_creator/src/OperationsFactory.cpp
1. Support for reshape operation added
2. Support to fetch vector operand values
Change-Id: I22ece517645615bebc3aa708ef87526c5da6c165
Signed-off-by: nitishat <nitisha.tomar@intel.com>
=> Added support for Reshape Operation

BasePreparedModel.cpp, ModelManager.cpp, ModelManager.h, ngraph_creator/Android.bp, ngraph_creator/include/NgraphNodes.hpp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/LSTM.hpp, ngraph_creator/operations/include/OperationsBase.hpp, ngraph_creator/operations/src/LSTM.cpp, ngraph_creator/operations/src/OperationsBase.cpp, ngraph_creator/src/NgraphNetworkCreator.cpp, ngraph_creator/src/NgraphNodes.cpp, ngraph_creator/src/OperationsFactory.cpp
Implemented LSTM operation for CPU
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> LSTM operation implementation

ngraph_creator/operations/src/LSTM.cpp
Added support for openvino 2021.2
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
=> changes to support LSTM implementation for openvino 2021.2

ModelManager.cpp, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/Softmax.hpp, ngraph_creator/operations/src/Reshape.cpp, ngraph_creator/operations/src/Softmax.cpp, ngraph_creator/src/OperationsFactory.cpp
Implemented Softmax operation.
Added support for stretch dimensions in reshape operations.
Signed-off-by: nitishat <nitisha.tomar@intel.com>
=> Implementation of Softmax and stretch dimensions in reshape

intel_nn_hal/GnaPreparedModel.cpp, intel_nn_hal/GnaPreparedModel.h
- Fix build errors related to PERF_COUNTERS 
- Fix error where network is loaded twice 
- Fix Infer Calls counter
=> Fix bugs related to PERF_COUNTERS

BUILD.gn, BasePreparedModel.h, IENetwork.cpp, cpu/CpuPreparedModel.cpp, ngraph_creator/src/NgraphNodes.cpp, service.cpp, utils.h
- Add BUILD.gn file for compilation
- Change file paths for chromeos
=> Changes needed to build for ChromeOS

ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/Max_Pool_2d.hpp, ngraph_creator/operations/src/Max_Pool_2d.cpp, ngraph_creator/src/OperationsFactory.cpp
=> Implementation of MAX_POOL_2D operation

ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/Average_Pool_2D.hpp, ngraph_creator/operations/src/Average_Pool_2D.cpp, ngraph_creator/src/OperationsFactory.cpp
Implemented AveragePool operation
Signed-off-by: nitishat <nitisha.tomar@intel.com>
=> Adding AveragePool operation implementation

ngraph_creator/operations/include/LSTM.hpp, ngraph_creator/operations/src/LSTM.cpp
FIxed LayerNorm LSTM calculation
Signed-off-by: Nagamani Chennuboina <nagamani.chennuboina@intel.com>
**=======================================================
=============== Summary ===============
Total Run time: 10m 47s
2/2 modules completed
Total Tests       : 29912
PASSED            : 10244
FAILED            : 18
IGNORED           : 19650
============== End of Results ==============
============================================**
=> LSTM LayerNorm VTS fix

BasePreparedModel.cpp, Driver.cpp, ModelManager.cpp, ModelManager.h, ngraph_creator/operations/include/NgraphHelper.hpp, ngraph_creator/operations/include/OperationsBase.hpp, ngraph_creator/operations/src/Add.cpp, ngraph_creator/operations/src/Concat.cpp, ngraph_creator/operations/src/Conv_2d.cpp, ngraph_creator/operations/src/OperationsBase.cpp, ngraph_creator/operations/src/Pad.cpp, ngraph_creator/operations/src/Pad_V2.cpp, ngraph_creator/operations/src/Reshape.cpp, ngraph_creator/operations/src/Topk_V2.cpp, ngraph_creator/operations/src/Transpose.cpp, ngraph_creator/src/NgraphNetworkCreator.cpp, utils.cpp, utils.h
Fixed fatal crashes observed during CTS run.
Improved logging and validation logic.
Merged with ArgMax/Min:
CTS:
=============== Summary ===============
Total Run time: 1h 28m 36s
2/2 modules completed
Total Tests       : 130076
PASSED            : 127082
FAILED            : 2994
============== End of Results ==============
VTS :
=============== Summary ===============
Total Run time: 23m 14s
2/2 modules completed
Total Tests       : 29912
PASSED            : 10392
FAILED            : 66
IGNORED           : 19454
============== End of Results ==============
=> Fix cts crashes

gna_driver.cpp, intel_nn_hal/Dequantize.h, intel_nn_hal/Driver.cpp, intel_nn_hal/Driver.h, intel_nn_hal/EmbeddingLookup.h, intel_nn_hal/GnaPreparedModel.cpp, intel_nn_hal/GnaPreparedModel.h, intel_nn_hal/PreparedModel.cpp, intel_nn_hal/PreparedModel.h, intel_nn_hal/Quantize.h, intel_nn_hal/Utils.cpp, intel_nn_hal/Utils.h, intel_nn_hal/graphAPI/GnaNetwork.cpp, intel_nn_hal/graphAPI/GnaNetwork.h, intel_nn_hal/graphAPI/IRBuilder.cpp, intel_nn_hal/graphAPI/IRBuilder.h
Address CTS/VTS issues for Intel GNA HAL.
Enable Joint network for Google ASR.
=> Cros cts wip

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/Channel_Shuffle.hpp, ngraph_creator/operations/src/Channel_Shuffle.cpp, ngraph_creator/src/OperationsFactory.cpp
Added new operation Channel_Shuffle.
VTS result:
=============== Summary ===============
Total Run time: 9m 23s
2/2 modules completed
Total Tests       : 29912
PASSED            : 10680
FAILED            : 18
IGNORED           : 19214
============== End of Results ==============
CTS result:
=============== Summary ===============
Total Run time: 38m 24s
2/2 modules completed
Total Tests       : 130076
PASSED            : 127233
FAILED            : 2843
============== End of Results ==============
=> Implementation of Channel_Shuffle operation

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/L2_Normalization.hpp, ngraph_creator/operations/src/L2_Normalization.cpp, ngraph_creator/src/OperationsFactory.cpp
**VTS:
=======================================================
=============== Summary ===============
Total Run time: 12m 37s
2/2 modules completed
Total Tests       : 29912
PASSED            : 12398
FAILED            : 2
IGNORED           : 17512
============== End of Results ==============
============================================**
**CTS:
=======================================================
=============== Summary ===============
Total Run time: 52m 50s
2/2 modules completed
Total Tests       : 130076
PASSED            : 127059
FAILED            : 3017
============== End of Results ==============
============================================**
=> L2_Normalization operation implementation

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/Instance_Normalization.hpp, ngraph_creator/operations/src/Instance_Normalization.cpp, ngraph_creator/src/OperationsFactory.cpp
Tested for input FP32.
VTS
[----------] Global test environment tear-down
[==========] 90 tests from 3 test suites ran. (1453 ms total)
[  PASSED  ] 60 tests.
[  SKIPPED ] 30 tests
CTS
[----------] Global test environment tear-down
[==========] 216 tests from 4 test suites ran. (2939 ms total)
[  PASSED  ] 216 tests.
=> Added support for Instance normalization

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/ResizeBilinear.hpp, ngraph_creator/operations/src/ResizeBilinear.cpp, ngraph_creator/src/OperationsFactory.cpp
Adds support for Resize bilinear operation for FLOAT32 and QUANt8 type
Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>
=> Add support for Resize Bilinear operation

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/Grouped_Conv_2d.hpp, ngraph_creator/operations/src/Grouped_Conv_2d.cpp, ngraph_creator/src/OperationsFactory.cpp
Add GroupedConv2D operation implementation
Tested PASS by "cros_nnapi_vts_1_2 --gtest_filter=*grouped_conv2d"
Signed-off-by: Cooper Chiou <cooper.chiou@intel.com>
=> Add support for GroupedConv2D operation

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/ResizeNearestNeighbor.hpp, ngraph_creator/operations/src/ResizeNearestNeighbor.cpp, ngraph_creator/src/OperationsFactory.cpp
Adds support for Nearest Neighbor resizing
Supports FLOAT32 and QUANT8_ASYMM type
Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>
=> Add support for Resize Nearest Neighbor operation

BUILD.gn, BasePreparedModel.cpp, BasePreparedModel.h, ModelManager.cpp, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/L2Pooling2D.hpp, ngraph_creator/operations/src/Concat.cpp, ngraph_creator/operations/src/Conv_2d.cpp, ngraph_creator/operations/src/Depthwise_Conv_2d.cpp, ngraph_creator/operations/src/L2Pooling2D.cpp, ngraph_creator/operations/src/L2_Normalization.cpp, ngraph_creator/operations/src/LSTM.cpp, ngraph_creator/operations/src/Max_Pool_2d.cpp, ngraph_creator/operations/src/Pad.cpp, ngraph_creator/operations/src/Pad_V2.cpp, ngraph_creator/operations/src/Quantize.cpp, ngraph_creator/operations/src/ROI_Pooling.cpp, ngraph_creator/operations/src/Reduce_Max.cpp, ngraph_creator/operations/src/Reduce_Sum.cpp, ngraph_creator/operations/src/Reshape.cpp, ngraph_creator/operations/src/Space_To_Batch.cpp, ngraph_creator/operations/src/Split.cpp, ngraph_creator/operations/src/Transpose_Conv_2D.cpp, ngraph_creator/src/NgraphNetworkCreator.cpp, ngraph_creator/src/NgraphNodes.cpp, ngraph_creator/src/OperationsFactory.cpp, utils.cpp, utils.h
- Supports only FP32 inputs
- Fix coding style issues
- Fix compiler warnings
Signed-off-by: P Raviraj Sitaram <raviraj.p.sitaram@intel.com>
=> Add support for L2_POOLING_2D operation

ngraph_creator/operations/src/Grouped_Conv_2d.cpp
Signed-off-by: Cooper Chiou <cooper.chiou@intel.com>
=> Add TENSOR_QUANT8_SYMM_PER_CHANNEL support for Grouped_Conv_2d

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/OperationsBase.hpp, ngraph_creator/operations/include/ROI_Align.hpp, ngraph_creator/operations/src/ROI_Align.cpp, ngraph_creator/src/OperationsFactory.cpp
Zero sized input is not supported.
Signed-Off-by: Vijeetkumar Benni <vijeetkumar.benni@intel.com>
=> Added support for ROI Align

BUILD.gn, ngraph_creator/Android.bp, ngraph_creator/include/OperationsFactory.hpp, ngraph_creator/operations/include/HardSwish.hpp, ngraph_creator/operations/src/HardSwish.cpp, ngraph_creator/src/OperationsFactory.cpp
Adds support for Hard Swish operator for all supported types
Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>
=> Add support for Hard swish operator

ngraph_creator/operations/src/ResizeBilinear.cpp, ngraph_creator/operations/src/ResizeNearestNeighbor.cpp
Adds Float16 support for ResizeBilinear and ResizeNearestNeighbor
Signed-off-by: Ritul Jasuja <ritul.jasuja@intel.com>
=> Add Float16 support for Resize Bilinear and Resize Nearest Neighbor op

ngraph_creator/operations/src/HardSwish.cpp
Fix issue #147
Signed-off-by: Reagan Lopez <reagan.lopez@intel.com>
=> Fix clang-format error

ngraph_creator/operations/src/Add.cpp
Fix issue #144
Signed-off-by: Reagan Lopez <reagan.lopez@intel.com>
=> Fix validation error in Add operation

ngraph_creator/operations/src/Add.cpp
=> Fix clang format error
